import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavWithAction from "./components/navigation/navbar";
import JobPostForm from "./components/job/postform";
import JobsView from "./components/job/jobsview";
import HorizontalJobview from "./components/job/horizontaljobcard";

const Jobs = ["test", "test2"];

const Home: NextPage = () => {
  return (
    <>
      <NavWithAction />

      <div className={styles.container}>
        <Head>
          <title>Create App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          {/* {Jobs.map((job) => (
            <JobCard job={job} key={job}></JobCard>
          ))} */}
          <HorizontalJobview />
          {/* <JobsView /> */}
          {/* <JobPostForm /> */}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default Home;
